swagger: '2.0'
info:
  title: ts api
  description: ts api
  version: 1.0.0
produces:
  - application/json
paths:
  /raw:
    get:
      tags:
        - RawData
      operationId: getRawData
      summary: get RawData
      description: get RawData
      parameters:
        - in: query
          name: interval
          type: string
          required: true
        - in: query
          name: start
          type: number
          required: true
        - in: query
          name: end
          type: number
          required: true
      responses:
        '200':
          description: get RawData
          schema:
            $ref: '#/definitions/RawDataResponse'

  /market_break_points:
    get:
      tags:
        - RawData
      operationId: getMarketBreakPoint
      summary: get Market Break Points
      description: get Market Break Points
      responses:
        '200':
          description: get Market Break Points
          schema:
            $ref: '#/definitions/MarketBreakPointResponse'

definitions:

  RawDataResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/RawData'
      query_string:
        type: string

  RawData:
    type: object
    properties:
      timestamp:
        type: integer
      open:
        type: number
      high:
        type: number
      low:
        type: number
      close:
        type: number
      volume:
        type: number

  MarketBreakPointResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/MarketBreakPoint'
      query_string:
        type: string

  MarketBreakPoint:
    type: object
    properties:
      timestamp:
        type: string