swagger: '2.0'
info:
  title: ts api
  description: ts api
  version: 1.0.0
produces:
  - application/json
paths:
  /raw:
    get:
      tags:
        - RawData
      operationId: getRawData
      summary: get RawData
      description: get RawData
      parameters:
        - in: query
          name: interval
          type: string
          required: true
      responses:
        '200':
          description: get RawData
          schema:
            type: array
            items:
              $ref: '#/definitions/RawData'

definitions:
  RawData:
    type: object
    properties:
      timestamp:
        type: integer
      open:
        type: number
      high:
        type: number
      low:
        type: number
      close:
        type: number
      volume:
        type: number
