openapi: 3.0.1
info:
  title: ts api
  description: ts api
  version: 1.0.0
servers:
- url: /
paths:
  /raw:
    get:
      tags:
      - RawData
      summary: get RawData
      description: get RawData
      operationId: get_raw_data
      parameters:
      - name: interval
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: start
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
      - name: end
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: get RawData
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RawDataResponse'
      x-openapi-router-controller: swagger_server.controllers.raw_data_controller
  /market_break_points:
    get:
      tags:
      - RawData
      summary: get Market Break Points
      description: get Market Break Points
      operationId: get_market_break_point
      responses:
        "200":
          description: get Market Break Points
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketBreakPointResponse'
      x-openapi-router-controller: swagger_server.controllers.raw_data_controller
  /models:
    get:
      tags:
      - Model
      summary: get Model list
      description: get Model list
      operationId: get_models
      responses:
        "200":
          description: get Model list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
      x-openapi-router-controller: swagger_server.controllers.model_controller
    post:
      tags:
      - Model
      summary: add or update Model
      description: add or update Model
      operationId: set_model
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Model'
        required: true
      responses:
        "200":
          description: add or update Model success
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.model_controller
  /sample_types:
    get:
      tags:
      - Model
      summary: get sample type list
      description: get sample type list
      operationId: get_sample_types
      responses:
        "200":
          description: get sample type list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleTypes'
      x-openapi-router-controller: swagger_server.controllers.model_controller
  /samples/summary:
    post:
      tags:
      - Sample
      summary: get Sample Summary
      description: get Sample Summary
      operationId: get_sample_summary
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleSummaryRequest'
        required: true
      responses:
        "200":
          description: get Sample Summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleSummaryResponse'
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.sample_controller
  /samples:
    get:
      tags:
      - Sample
      summary: get Sample list
      description: get Sample list
      operationId: get_samples
      responses:
        "200":
          description: get Sample list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SamplesResponse'
      x-openapi-router-controller: swagger_server.controllers.sample_controller
    post:
      tags:
      - Sample
      summary: add or update sample
      description: add or update sample
      operationId: set_samples
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SamplesRequest'
        required: true
      responses:
        "200":
          description: add or update sample success
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.sample_controller
  /dataset:
    get:
      tags:
      - Sample
      summary: get data set
      description: get data set
      operationId: get_data_sets
      responses:
        "200":
          description: get data set
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSetResponse'
      x-openapi-router-controller: swagger_server.controllers.sample_controller
    post:
      tags:
      - Sample
      summary: add or update data set
      description: add or update data set
      operationId: set_data_set
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataSet'
        required: true
      responses:
        "200":
          description: add or update data set success
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.sample_controller
  /fit:
    get:
      tags:
      - Fit
      summary: get fit status
      description: get fit status
      operationId: get_fits
      responses:
        "200":
          description: get fit status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FitsResponse'
      x-openapi-router-controller: swagger_server.controllers.fit_controller
    post:
      tags:
      - Fit
      summary: begin or cancel a fit process
      description: begin or cancel a fit process
      operationId: set_fit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FitRequest'
        required: true
      responses:
        "200":
          description: begin or cancel a fit process
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.fit_controller
components:
  schemas:
    RawDataResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/RawData'
        query_string:
          type: string
      example:
        data:
        - volume: 2.3021358869347655
          high: 1.4658129805029452
          low: 5.962133916683182
          close: 5.637376656633329
          open: 6.027456183070403
          timestamp: 0
        - volume: 2.3021358869347655
          high: 1.4658129805029452
          low: 5.962133916683182
          close: 5.637376656633329
          open: 6.027456183070403
          timestamp: 0
        query_string: query_string
    RawData:
      type: object
      properties:
        timestamp:
          type: integer
        open:
          type: number
        high:
          type: number
        low:
          type: number
        close:
          type: number
        volume:
          type: number
      example:
        volume: 2.3021358869347655
        high: 1.4658129805029452
        low: 5.962133916683182
        close: 5.637376656633329
        open: 6.027456183070403
        timestamp: 0
    MarketBreakPointResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/MarketBreakPoint'
        query_string:
          type: string
      example:
        data:
        - timestamp: timestamp
        - timestamp: timestamp
        query_string: query_string
    MarketBreakPoint:
      type: object
      properties:
        timestamp:
          type: string
      example:
        timestamp: timestamp
    Model:
      type: object
      properties:
        model:
          type: string
        description:
          type: string
        params:
          type: string
      example:
        description: description
        model: model
        params: params
    SampleTypes:
      type: object
      properties:
        type:
          type: string
        description:
          type: string
      example:
        description: description
        type: type
    SamplesResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Samples'
        query_string:
          type: string
      example:
        data:
        - uid: uid
          sample_data:
          - volume: 2.3021358869347655
            high: 1.4658129805029452
            low: 5.962133916683182
            close: 5.637376656633329
            open: 6.027456183070403
            timestamp: 0
          - volume: 2.3021358869347655
            high: 1.4658129805029452
            low: 5.962133916683182
            close: 5.637376656633329
            open: 6.027456183070403
            timestamp: 0
          extra_data:
          - null
          - null
          value: 0.8008281904610115
        - uid: uid
          sample_data:
          - volume: 2.3021358869347655
            high: 1.4658129805029452
            low: 5.962133916683182
            close: 5.637376656633329
            open: 6.027456183070403
            timestamp: 0
          - volume: 2.3021358869347655
            high: 1.4658129805029452
            low: 5.962133916683182
            close: 5.637376656633329
            open: 6.027456183070403
            timestamp: 0
          extra_data:
          - null
          - null
          value: 0.8008281904610115
        query_string: query_string
    SamplesRequest:
      type: array
      items:
        $ref: '#/components/schemas/Samples'
    Samples:
      type: object
      properties:
        uid:
          type: string
        sample_data:
          type: array
          items:
            $ref: '#/components/schemas/RawData'
        value:
          type: number
        extra_data:
          type: array
          items:
            $ref: '#/components/schemas/RawData'
      example:
        uid: uid
        sample_data:
        - volume: 2.3021358869347655
          high: 1.4658129805029452
          low: 5.962133916683182
          close: 5.637376656633329
          open: 6.027456183070403
          timestamp: 0
        - volume: 2.3021358869347655
          high: 1.4658129805029452
          low: 5.962133916683182
          close: 5.637376656633329
          open: 6.027456183070403
          timestamp: 0
        extra_data:
        - null
        - null
        value: 0.8008281904610115
    DataSetResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DataSet'
        query_string:
          type: string
      example:
        data:
        - uid_to: uid_to
          name: name
          count: 6.027456183070403
          id: 0.8008281904610115
          uid_from: uid_from
        - uid_to: uid_to
          name: name
          count: 6.027456183070403
          id: 0.8008281904610115
          uid_from: uid_from
        query_string: query_string
    DataSet:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        uid_from:
          type: string
        uid_to:
          type: string
        count:
          type: number
      example:
        uid_to: uid_to
        name: name
        count: 6.027456183070403
        id: 0.8008281904610115
        uid_from: uid_from
    SampleSummaryRequest:
      type: array
      items:
        $ref: '#/components/schemas/SampleSummaryRequestItem'
    SampleSummaryRequestItem:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
    SampleSummaryResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SampleSummaryResponseItem'
        query_string:
          type: string
      example:
        data:
        - count: 0.8008281904610115
          from: from
          to: to
        - count: 0.8008281904610115
          from: from
          to: to
        query_string: query_string
    SampleSummaryResponseItem:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        count:
          type: number
      example:
        count: 0.8008281904610115
        from: from
        to: to
    FitsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Fit'
        query_string:
          type: string
      example:
        data:
        - data_set:
            uid_to: uid_to
            name: name
            count: 6.027456183070403
            id: 0.8008281904610115
            uid_from: uid_from
          started: started
          finished: finished
          id: 0.8008281904610115
          status: status
        - data_set:
            uid_to: uid_to
            name: name
            count: 6.027456183070403
            id: 0.8008281904610115
            uid_from: uid_from
          started: started
          finished: finished
          id: 0.8008281904610115
          status: status
        query_string: query_string
    Fit:
      type: object
      properties:
        id:
          type: number
        data_set:
          $ref: '#/components/schemas/DataSet'
        started:
          type: string
        finished:
          type: string
        status:
          type: string
      example:
        data_set:
          uid_to: uid_to
          name: name
          count: 6.027456183070403
          id: 0.8008281904610115
          uid_from: uid_from
        started: started
        finished: finished
        id: 0.8008281904610115
        status: status
    FitRequest:
      type: object
      properties:
        id:
          type: number
        data_set:
          type: number
x-original-swagger-version: "2.0"

