# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MarketBreakPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: str=None):  # noqa: E501
        """MarketBreakPoint - a model defined in Swagger

        :param timestamp: The timestamp of this MarketBreakPoint.  # noqa: E501
        :type timestamp: str
        """
        self.swagger_types = {
            'timestamp': str
        }

        self.attribute_map = {
            'timestamp': 'timestamp'
        }
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'MarketBreakPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MarketBreakPoint of this MarketBreakPoint.  # noqa: E501
        :rtype: MarketBreakPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this MarketBreakPoint.


        :return: The timestamp of this MarketBreakPoint.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this MarketBreakPoint.


        :param timestamp: The timestamp of this MarketBreakPoint.
        :type timestamp: str
        """

        self._timestamp = timestamp
