# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.market_break_point import MarketBreakPoint  # noqa: F401,E501
from swagger_server import util


class MarketBreakPointResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[MarketBreakPoint]=None, query_string: str=None):  # noqa: E501
        """MarketBreakPointResponse - a model defined in Swagger

        :param data: The data of this MarketBreakPointResponse.  # noqa: E501
        :type data: List[MarketBreakPoint]
        :param query_string: The query_string of this MarketBreakPointResponse.  # noqa: E501
        :type query_string: str
        """
        self.swagger_types = {
            'data': List[MarketBreakPoint],
            'query_string': str
        }

        self.attribute_map = {
            'data': 'data',
            'query_string': 'query_string'
        }
        self._data = data
        self._query_string = query_string

    @classmethod
    def from_dict(cls, dikt) -> 'MarketBreakPointResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MarketBreakPointResponse of this MarketBreakPointResponse.  # noqa: E501
        :rtype: MarketBreakPointResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[MarketBreakPoint]:
        """Gets the data of this MarketBreakPointResponse.


        :return: The data of this MarketBreakPointResponse.
        :rtype: List[MarketBreakPoint]
        """
        return self._data

    @data.setter
    def data(self, data: List[MarketBreakPoint]):
        """Sets the data of this MarketBreakPointResponse.


        :param data: The data of this MarketBreakPointResponse.
        :type data: List[MarketBreakPoint]
        """

        self._data = data

    @property
    def query_string(self) -> str:
        """Gets the query_string of this MarketBreakPointResponse.


        :return: The query_string of this MarketBreakPointResponse.
        :rtype: str
        """
        return self._query_string

    @query_string.setter
    def query_string(self, query_string: str):
        """Sets the query_string of this MarketBreakPointResponse.


        :param query_string: The query_string of this MarketBreakPointResponse.
        :type query_string: str
        """

        self._query_string = query_string
