# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RawData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, email: str=None, last_login: str=None, deleted_at: str=None):  # noqa: E501
        """RawData - a model defined in Swagger

        :param id: The id of this RawData.  # noqa: E501
        :type id: int
        :param name: The name of this RawData.  # noqa: E501
        :type name: str
        :param email: The email of this RawData.  # noqa: E501
        :type email: str
        :param last_login: The last_login of this RawData.  # noqa: E501
        :type last_login: str
        :param deleted_at: The deleted_at of this RawData.  # noqa: E501
        :type deleted_at: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'email': str,
            'last_login': str,
            'deleted_at': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'email': 'email',
            'last_login': 'last_login',
            'deleted_at': 'deleted_at'
        }
        self._id = id
        self._name = name
        self._email = email
        self._last_login = last_login
        self._deleted_at = deleted_at

    @classmethod
    def from_dict(cls, dikt) -> 'RawData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RawData of this RawData.  # noqa: E501
        :rtype: RawData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this RawData.


        :return: The id of this RawData.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this RawData.


        :param id: The id of this RawData.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this RawData.


        :return: The name of this RawData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this RawData.


        :param name: The name of this RawData.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this RawData.


        :return: The email of this RawData.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this RawData.


        :param email: The email of this RawData.
        :type email: str
        """

        self._email = email

    @property
    def last_login(self) -> str:
        """Gets the last_login of this RawData.


        :return: The last_login of this RawData.
        :rtype: str
        """
        return self._last_login

    @last_login.setter
    def last_login(self, last_login: str):
        """Sets the last_login of this RawData.


        :param last_login: The last_login of this RawData.
        :type last_login: str
        """

        self._last_login = last_login

    @property
    def deleted_at(self) -> str:
        """Gets the deleted_at of this RawData.


        :return: The deleted_at of this RawData.
        :rtype: str
        """
        return self._deleted_at

    @deleted_at.setter
    def deleted_at(self, deleted_at: str):
        """Sets the deleted_at of this RawData.


        :param deleted_at: The deleted_at of this RawData.
        :type deleted_at: str
        """

        self._deleted_at = deleted_at
