# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RawData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: int=None, open: float=None, high: float=None, low: float=None, close: float=None, volume: float=None):  # noqa: E501
        """RawData - a model defined in Swagger

        :param timestamp: The timestamp of this RawData.  # noqa: E501
        :type timestamp: int
        :param open: The open of this RawData.  # noqa: E501
        :type open: float
        :param high: The high of this RawData.  # noqa: E501
        :type high: float
        :param low: The low of this RawData.  # noqa: E501
        :type low: float
        :param close: The close of this RawData.  # noqa: E501
        :type close: float
        :param volume: The volume of this RawData.  # noqa: E501
        :type volume: float
        """
        self.swagger_types = {
            'timestamp': int,
            'open': float,
            'high': float,
            'low': float,
            'close': float,
            'volume': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'open': 'open',
            'high': 'high',
            'low': 'low',
            'close': 'close',
            'volume': 'volume'
        }
        self._timestamp = timestamp
        self._open = open
        self._high = high
        self._low = low
        self._close = close
        self._volume = volume

    @classmethod
    def from_dict(cls, dikt) -> 'RawData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RawData of this RawData.  # noqa: E501
        :rtype: RawData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> int:
        """Gets the timestamp of this RawData.


        :return: The timestamp of this RawData.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: int):
        """Sets the timestamp of this RawData.


        :param timestamp: The timestamp of this RawData.
        :type timestamp: int
        """

        self._timestamp = timestamp

    @property
    def open(self) -> float:
        """Gets the open of this RawData.


        :return: The open of this RawData.
        :rtype: float
        """
        return self._open

    @open.setter
    def open(self, open: float):
        """Sets the open of this RawData.


        :param open: The open of this RawData.
        :type open: float
        """

        self._open = open

    @property
    def high(self) -> float:
        """Gets the high of this RawData.


        :return: The high of this RawData.
        :rtype: float
        """
        return self._high

    @high.setter
    def high(self, high: float):
        """Sets the high of this RawData.


        :param high: The high of this RawData.
        :type high: float
        """

        self._high = high

    @property
    def low(self) -> float:
        """Gets the low of this RawData.


        :return: The low of this RawData.
        :rtype: float
        """
        return self._low

    @low.setter
    def low(self, low: float):
        """Sets the low of this RawData.


        :param low: The low of this RawData.
        :type low: float
        """

        self._low = low

    @property
    def close(self) -> float:
        """Gets the close of this RawData.


        :return: The close of this RawData.
        :rtype: float
        """
        return self._close

    @close.setter
    def close(self, close: float):
        """Sets the close of this RawData.


        :param close: The close of this RawData.
        :type close: float
        """

        self._close = close

    @property
    def volume(self) -> float:
        """Gets the volume of this RawData.


        :return: The volume of this RawData.
        :rtype: float
        """
        return self._volume

    @volume.setter
    def volume(self, volume: float):
        """Sets the volume of this RawData.


        :param volume: The volume of this RawData.
        :type volume: float
        """

        self._volume = volume
