/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * ts api
 * ts api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {

    constructor(protected configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface RawData
 */
export interface RawData {
    /**
     * 
     * @type {number}
     * @memberof RawData
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RawData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RawData
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof RawData
     */
    lastLogin?: string;
    /**
     * 
     * @type {string}
     * @memberof RawData
     */
    deletedAt?: string;
}
/**
 * RawDataApi - fetch parameter creator
 * @export
 */
export const RawDataApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * get RawData
         * @summary get RawData
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRawData(options: any = {}): FetchArgs {
            const localVarPath = `/raw`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RawDataApi - functional programming interface
 * @export
 */
export const RawDataApiFp = function(configuration?: Configuration) {
    return {
        /**
         * get RawData
         * @summary get RawData
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRawData(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<RawData>> {
            const localVarFetchArgs = RawDataApiFetchParamCreator(configuration).getRawData(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * RawDataApi - factory interface
 * @export
 */
export const RawDataApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * get RawData
         * @summary get RawData
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRawData(options?: any) {
            return RawDataApiFp(configuration).getRawData(options)(fetch, basePath);
        },
    };
};

/**
 * RawDataApi - object-oriented interface
 * @export
 * @class RawDataApi
 * @extends {BaseAPI}
 */
export class RawDataApi extends BaseAPI {
    /**
     * get RawData
     * @summary get RawData
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RawDataApi
     */
    public getRawData(options?: any) {
        return RawDataApiFp(this.configuration).getRawData(options)(this.fetch, this.basePath);
    }

}
